Document: mraa
Title: Debian mraa Manual
Author: <insert document author here>
Abstract: This manual describes what mraa is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mraa/mraa.sgml.gz

Format: postscript
Files: /usr/share/doc/mraa/mraa.ps.gz

Format: text
Files: /usr/share/doc/mraa/mraa.text.gz

Format: HTML
Index: /usr/share/doc/mraa/html/index.html
Files: /usr/share/doc/mraa/html/*.html
